import type { Agent, Config, Decision, Feature, Progress } from "./schemas/index.js";

export const AGENTS_MD_MARKER = "<!-- generated by harness-manager -->";

export interface HarnessSnapshot {
  config: Config;
  agents: Agent[];
  features: Feature[];
  progress: Progress;
  decisions: Decision[];
}

export function generateAgentsMd(snapshot: HarnessSnapshot): string {
  const { config, agents, features, progress } = snapshot;
  const lines: string[] = [];

  lines.push(AGENTS_MD_MARKER);
  lines.push("<!-- do not hand-edit; regenerated by harness-manager -->");
  lines.push("");
  lines.push(`# ${config.name}`);
  if (config.description) {
    lines.push("");
    lines.push(config.description);
  }

  lines.push("");
  lines.push("## Hard Constraints");
  if (config.hardConstraints.length) {
    for (const c of config.hardConstraints) lines.push(`- ${c}`);
  } else {
    lines.push("_none_");
  }

  lines.push("");
  lines.push("## Agents");
  if (agents.length) {
    for (const a of agents) lines.push(`- **${a.id}** (${a.role})`);
  } else {
    lines.push("_none_");
  }

  const active = features.filter((f) => f.state === "active");
  lines.push("");
  lines.push("## Active Features");
  if (active.length) {
    for (const f of active) lines.push(`- **${f.id}**: ${f.behavior} — verify: \`${f.verification}\``);
  } else {
    lines.push("_none_");
  }

  lines.push("");
  lines.push("## Next Steps");
  if (progress.nextSteps.length) {
    for (const s of progress.nextSteps) lines.push(`- ${s}`);
  } else {
    lines.push("_none_");
  }

  return lines.join("\n") + "\n";
}
